# Generated by Django 4.0.5 on 2022-07-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='participant',
            field=models.ForeignKey(choices=[(4, 'excellent'), (3, 'very good'), (2, 'good'), (1, 'bad')], on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='users.participant'),
        ),
    ]
