# Generated by Django 4.0.5 on 2022-07-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentss',
            new_name='Comments',
        ),
    ]
