# Generated by Django 4.0.5 on 2022-07-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_comment_culture_and_speed_of_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Speed_and_quality_of_defect_elimination',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
