# Generated by Django 4.0.5 on 2022-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_comment_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Expert', 'Expert')], default='Entrepreneur', max_length=100)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='roles',
            field=models.ManyToManyField(blank=True, to='users.role'),
        ),
    ]
