# Generated by Django 4.0.5 on 2022-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_comment_speed_and_quality_of_defect_elimination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Culture_and_speed_of_communication',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Project_management_level',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Quality_of_performance_of_works_services_supplies',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Timeliness_of_performance_of_works_services_deliveries',
            field=models.FloatField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
