# Generated by Django 4.0.5 on 2022-07-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_comment_culture_and_speed_of_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Culture_and_speed_of_communication',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], verbose_name='Культура та швидкість комунікації'),
        ),
    ]
