# Generated by Django 4.0.5 on 2022-07-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_comment_project_management_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Quality_of_performance_of_works_services_supplies',
            new_name='Quality_of_performance',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Timeliness_of_performance_of_works_services_deliveries',
            new_name='Timeliness_of_performance',
        ),
    ]
