# Generated by Django 4.0.5 on 2022-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_quality_of_performance_of_works_services_supplies_comment_quality_of_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Culture_and_speed_of_communication',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4'), (3.5, '3,5'), (3, '3'), (2.5, '2,5'), (2, '2'), (1.5, '1,5'), (1, '1')], verbose_name='Культура та швидкість комунікації'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Project_management_level',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4'), (3.5, '3,5'), (3, '3'), (2.5, '2,5'), (2, '2'), (1.5, '1,5'), (1, '1')], verbose_name='Рівень проджект менеджменту'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Quality_of_performance',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4'), (3.5, '3,5'), (3, '3'), (2.5, '2,5'), (2, '2'), (1.5, '1,5'), (1, '1')], verbose_name='Якість виконання робіт/послуг/поставок'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Speed_and_quality_of_defect_elimination',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4'), (3.5, '3,5'), (3, '3'), (2.5, '2,5'), (2, '2'), (1.5, '1,5'), (1, '1')], verbose_name='Швидкість та якість усунення дефектів'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Timeliness_of_performance',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4'), (3.5, '3,5'), (3, '3'), (2.5, '2,5'), (2, '2'), (1.5, '1,5'), (1, '1')], verbose_name='Своєчасність виконання робіт/послуг/поставок'),
        ),
    ]
