# Generated by Django 4.0.5 on 2022-07-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_comment_culture_and_speed_of_communication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Culture_and_speed_of_communication',
            new_name='culture_and_speed_of_communication',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Project_management_level',
            new_name='project_management_level',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Quality_of_performance',
            new_name='quality_of_performance',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Speed_and_quality_of_defect_elimination',
            new_name='speed_and_quality_of_defect_elimination',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Timeliness_of_performance',
            new_name='timeliness_of_performance',
        ),
    ]
