# Generated by Django 4.0.5 on 2022-07-07 18:59

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=13, prefix='id_', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
