# Generated by Django 4.0.5 on 2022-07-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_role_project_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
