# Generated by Django 4.0.5 on 2022-07-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
